### ISSUE TITLE
Multiple Issues in Various Areas

### ISSUE THREAD

**Issue by GuardianMajor** [dtinth/dark-facebook#3] opened 2013-11-06 08:19 UTC
First off, I like your CSS quite a bit, I am not a big fan of the blue shading instead of making it truly dark theme with various shades of black/grey but none the less, clean and smooth. I like it.

However, there are a bunch of elements that are not right and I know there have been changes by Facebook intent on breaking anything that makes their crap look and function better but still pretty critical for usability at the moment and some are just annoying.

Here they are as best in order as I can make them with pictures too.

1) The drop down action menu that is on a post viewed all by itself has really pronounced lines and a double scrunch on the top which is just hideous:
![dark_css_action-menu](https://f.cloud.github.com/assets/5274181/1480745/71119202-46b8-11e3-888f-01917c71e491.png)

2) When you have message items the whole thing is grey and one usability issue is that you can't tell the difference between read and unread messages, the highlight is not honored but worse yet, when you archive the last item on the list, you get a white background, something got missed in the styling:
![dark_css_chat-archieved](https://f.cloud.github.com/assets/5274181/1480750/af3ff1e0-46b8-11e3-9a50-14aa798c520e.png)

3) In the message typing window, you can see the "smiley" menu icon is out of place and not consistent with the rest of the styling, while the pop up with the stickers looks good:
![dark_css_chat-smiley](https://f.cloud.github.com/assets/5274181/1480751/d19f1798-46b8-11e3-9e04-fa7dc05122f2.png)

4) The header at the top is horribly styled with colors just making it look broken and plain old hideous and inconsistent with a clean view, probably due to the graph search change but none the less:
![dark_css_header](https://f.cloud.github.com/assets/5274181/1480767/041845f0-46b9-11e3-9fb3-9c5de99cd22a.png)

5) When you go to the top right drop down of the profile and you click on help, you get this horribly transparent and mangled displayed menu which is unusable:
![dark_css_help-drop](https://f.cloud.github.com/assets/5274181/1480771/259c9514-46b9-11e3-8ca6-2be103b7fd8c.png)

6) Notification drop down doesn't distinguish between the read/unread items and they are look the same, making it very unusable:
![dark_css_notifications](https://f.cloud.github.com/assets/5274181/1480844/81ef872a-46bb-11e3-9d80-de80184670f6.png)

7) The meta items under viewing a picture, the icons don't blend, such as location:
![dark_css_picture_meta](https://f.cloud.github.com/assets/5274181/1480847/ad665a82-46bb-11e3-8473-78765fc5c01b.png)

8) The post options that appear in the bottom left are completely and utterly mangled:
![dark_css_post-options](https://f.cloud.github.com/assets/5274181/1480851/c902792e-46bb-11e3-94ef-b3e575cc2ea8.png)

9) The last two items of the profile drop down menu (Help and Report) are mangled together into one highlighted item:
![dark_css_profiles-drop](https://f.cloud.github.com/assets/5274181/1480853/e2edc3fc-46bb-11e3-9247-e86c726fe1c4.png)

10) Lastly, not sure if this can be fixed via the css code, but the non-rectangle icons anywhere, especially visible on the settings page have rough edges resulting in mangling of the icons view:
![dark_css_setting-icons](https://f.cloud.github.com/assets/5274181/1480863/20aed168-46bc-11e3-89d9-6a9dcb761290.png)

**Comment by dtinth** [comment] 2013-11-06 16:38
Thank you very much for such a detailed report! I don't have much time to maintain this style (and this stylesheet has become quite unmaintainable).

I do have a plan to rework on this style and make it easier for contributions. Again, Facebook just changes a lot of things and does a lot of A/B testing, so some of these things I cannot reproduce.

Some annoying bugs are caused by Facebook's high contrast mode. Only way to work around it is to change the way this style is created, which would require a huge amount of work...

I'll keep you updated when I finally find some time to work on the theme. Thanks again for your report.

**Comment by GuardianMajor** [comment] 2013-11-07 04:10
You are most welcome, only constructive participation can help make things better. I can imagine that it has become a hassle but I hope that you will follow with plans to rework it from scratch and I would be happy to help you. So yeah definitely let me know when you are up for reinventing this sucker and I'll be there. We can build the framework of it, then each of us can take a piece and work on it and finally combine to get it all done. I'm game, let me know when. You know how to reach me. In the meantime if you want to stay in touch friend me on FB (/GuardianMajor) and we can talk more there.

**Comment by auscompgeek** [comment] 2013-11-21 07:39
Number 8 is actually caused by Facebook adding a "highContrast" class to the body tag. Removing the highContrast class manually (through JavaScript (`document.documentElement.classList.remove("highContrast")`) or a DOM inspector) fixes that.

**Comment by dtinth** [comment] 2013-11-21 17:24
Hello, everyone.

I did some initial work on the second version of the theme (which is rewritten from scratch) that's going to make it easier to test, modify, and contribute to this theme.

It's called dark-facebook 2, or dfb2.

Now I'm experimenting with a lot of stuff. Hopefully I'll get the foundation stabilized within few weeks, so stay tuned.

https://github.com/dtinth/dark-facebook/tree/dfb2

**Comment by GuardianMajor** [comment] 2013-11-21 21:04
Yes I have noticed that high contrast but we need to figure out why its triggering, given that we are modifying the CSS on the client side, the FB code shouldn't be able to realize the change and trigger a script to change it, but maybe it does, not sure. We'll have to have to figure that one out.

Glad to hear your got started on a new version, I will check it out and give you feedback as I get them :+1:

**Comment by dtinth** [comment] 2013-11-21 23:20
Here's the reason why Facebook triggered high-contrast mode:

It's the theming approach that `dark-facebook` uses that triggers it. That's why I had to start from scratch.

The theming approach is this:
1. I set the background color of the page to black,
2. the color of all text to white,
3. remove all border colors,
4. make all elements have transparent background, and
5. start adding colors in from there.

The high-contrast mode checking routine creates an element, set some colors on it, and sees whether the colors are the still the same or not. Because dark-facebook also overrides the colors of that element (which cannot be reliably identified through CSS selectors), facebook triggers it.

Also, with that approach, any new UI elements that may appear on facebook will get a transparent background. So that's why there's a lot of problems with the current approach.

**Comment by GuardianMajor** [comment] 2013-11-22 21:11
Understood, thanks for the explanation. Yeah I figured that much, just wondering how we can prevent their code from triggering the mismatch, unfortunately might be difficult to do since we can't control how "THEIR" code validates stuff. You would think once the CSS for the page is loaded, everything inherits it and no need to individually validate it every time by FB but guess regardless of using AJAX interface, they still do. Curious. Might have something to do with the way the XHR is processed by the site.

**Comment by dtinth** [comment] 2014-03-15 14:45
Hi. Most of these seem to be fixed in the latest "dark-facebook 2" version, and is [now available on userstyles.org](http://userstyles.org/styles/95359/facebook-dark-facebook-2).

Also, I've tried to make it better organized so that it's easier to fix, implement new stuff, and for others to contribute to.

However, this theme is very far from complete. Since I styled only these things that's most frequently used. You can help me make this user style more complete. If you're interested, then please let me know! :D

**Closed as completed by dtinth** 2014-03-15 14:45 UTC

**Comment by GuardianMajor** [comment] 2014-03-16 22:46
@dtinth 
glad to hear it my friend, will give it a look, good work.
